# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: zohoho 4.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "zohoho".freeze
  s.version = "4.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["KentonWhite".freeze, "NicholasMartin".freeze, "Xymist".freeze]
  s.date = "2018-12-10"
  s.description = "Simple interface to zoho api".freeze
  s.email = ["jkentonwhite@gmail.com,".freeze, "nicholas.martin@marketdojo.com".freeze]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".byebug_history",
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "examples/print_task_list.rb",
    "lib/zohoho.rb",
    "lib/zohoho/account.rb",
    "lib/zohoho/authentication.rb",
    "lib/zohoho/connection.rb",
    "lib/zohoho/contact.rb",
    "lib/zohoho/crm.rb",
    "lib/zohoho/lead.rb",
    "lib/zohoho/zoho_object.rb",
    "spec/connection_spec.rb",
    "spec/crm_spec.rb",
    "spec/rails_helper.rb",
    "spec/vcr_cassettes/connection/call.yml",
    "spec/vcr_cassettes/crm/add_complicated_contact.yml",
    "spec/vcr_cassettes/crm/add_contact.yml",
    "spec/vcr_cassettes/crm/contact.yml",
    "spec/vcr_cassettes/crm/contact_single.yml",
    "spec/vcr_cassettes/crm/get_account_by_id.yml",
    "spec/vcr_cassettes/crm/get_contact_by_email.yml",
    "spec/vcr_cassettes/crm/get_contact_by_id.yml",
    "spec/vcr_cassettes/crm/note.yml",
    "zohoho.gemspec"
  ]
  s.homepage = "http://github.com/kwhite/zohoho".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.7.7".freeze
  s.summary = "Simple interface to zoho api".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<json>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<xml-simple>.freeze, [">= 0"])
      s.add_development_dependency(%q<bundler>.freeze, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>.freeze, [">= 1.6.0"])
      s.add_development_dependency(%q<pry>.freeze, [">= 0"])
      s.add_development_dependency(%q<pry-byebug>.freeze, [">= 0"])
    else
      s.add_dependency(%q<httparty>.freeze, [">= 0"])
      s.add_dependency(%q<json>.freeze, [">= 0"])
      s.add_dependency(%q<xml-simple>.freeze, [">= 0"])
      s.add_dependency(%q<bundler>.freeze, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>.freeze, [">= 1.6.0"])
      s.add_dependency(%q<pry>.freeze, [">= 0"])
      s.add_dependency(%q<pry-byebug>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<httparty>.freeze, [">= 0"])
    s.add_dependency(%q<json>.freeze, [">= 0"])
    s.add_dependency(%q<xml-simple>.freeze, [">= 0"])
    s.add_dependency(%q<bundler>.freeze, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>.freeze, [">= 1.6.0"])
    s.add_dependency(%q<pry>.freeze, [">= 0"])
    s.add_dependency(%q<pry-byebug>.freeze, [">= 0"])
  end
end

