# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = 'zohoho'
  s.version = '0.4.0'

  s.required_rubygems_version = Gem::Requirement.new('>= 0') if s.respond_to? :required_rubygems_version=
  s.authors = %w[KentonWhite NicholasMartin]
  s.date = '2018-05-16'
  s.description = 'Simple interface to zoho api'
  s.email = 'nicholas.martin@marketdojo.com'
  s.extra_rdoc_files = [
    'LICENSE.txt',
    'README.rdoc'
  ]
  s.files = [
    '.autotest',
    '.document',
    'Gemfile',
    'Gemfile.lock',
    'LICENSE.txt',
    'README.rdoc',
    'Rakefile',
    'VERSION',
    'autotest/discover.rb',
    'lib/zohoho.rb',
    'lib/zohoho/account.rb',
    'lib/zohoho/authentication.rb',
    'lib/zohoho/connection.rb',
    'lib/zohoho/contact.rb',
    'lib/zohoho/crm.rb',
    'lib/zohoho/lead.rb',
    'lib/zohoho/zoho_object.rb',
    'spec/connection_spec.rb',
    'spec/crm_spec.rb',
    'spec/fixtures/vcr_cassettes/connection/call.yml',
    'spec/fixtures/vcr_cassettes/crm/add_contact.yml',
    'spec/fixtures/vcr_cassettes/crm/add_complicated_contact.yml',
    'spec/fixtures/vcr_cassettes/crm/contact.yml',
    'spec/fixtures/vcr_cassettes/crm/contact_single.yml',
    'spec/fixtures/vcr_cassettes/crm/note.yml',
    'spec/spec_helper.rb',
    'zohoho.gemspec'
  ]
  s.homepage = 'http://github.com/kwhite/zohoho'
  s.licenses = ['MIT']
  s.require_paths = ['lib']
  s.rubygems_version = '1.5.2'
  s.summary = 'Simple interface to zoho api'

  if s.respond_to? :specification_version
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0')
      s.add_runtime_dependency('httparty', ['>= 0'])
      s.add_runtime_dependency('json', ['>= 0'])
      s.add_runtime_dependency('xml-simple', ['>= 0'])
      s.add_development_dependency('bundler', ['~> 1.0.0'])
      s.add_development_dependency('jeweler', ['~> 1.6.0'])
      s.add_development_dependency('rspec', ['>= 0'])
    else
      s.add_dependency('bundler', ['~> 1.0.0'])
      s.add_dependency('httparty', ['>= 0'])
      s.add_dependency('jeweler', ['~> 1.6.0'])
      s.add_dependency('json', ['>= 0'])
      s.add_dependency('rspec', ['>= 0'])
      s.add_dependency('xml-simple', ['>= 0'])
    end
  else
    s.add_dependency('httparty', ['>= 0'])
    s.add_dependency('json', ['>= 0'])
    s.add_dependency('xml-simple', ['>= 0'])
    s.add_dependency('xml-simple', ['>= 0'])
    s.add_dependency('xml-simple', ['>= 0'])
    s.add_dependency('xml-simple', ['>= 0'])
  end
end
